services:
  postgres:
    image: postgres:16
    container_name: pms-postgres
    environment:
      POSTGRES_DB: pms_backend_dev
      POSTGRES_USER: pms_user
      POSTGRES_PASSWORD: qazzxc12
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pms_user -d pms_backend_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  pms-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pms-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=pms_backend_dev;Username=pms_user;Password=qazzxc12
    ports:
      - "5001:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs

  pms-frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: pms-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
      - NODE_ENV=development
    depends_on:
      - pms-api
    volumes:
      - ./src/frontend:/app
      - /app/node_modules

volumes:
  postgres_data: